### ISSUE TITLE
ArrayIndexOutOfBoundsException: 527 on FRB import of disk history.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#126]
Paper dev 620
FAWE-Breaking dev 60
FAVS-Breaking dev 60

@boy0001 Running into this error when trying to import someone's disk history.

I'm trying to rollback a destroyed area due to using a version of FAWE before this commit. https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/f6b844e53c71a2243243bd44221bf561b1090a38 The WorldEdit schematic paste operation broke the player's entire chunk area.

When trying to ``frb`` or ``undo`` with the specified worldediting player's name, no rollback occurs.

Config
https://paste.ubuntu.com/p/ShJy8Cbxxn/

```
[01:22:54] [Server thread/INFO]: player issued server command: //frb #import
[01:22:54] [Craft Scheduler Thread - 89/INFO]: WorldEdit: player (in "world"): /frb #import
[01:22:54] [Craft Scheduler Thread - 89/ERROR]: An unexpected error occurred while handling a FAWE command
java.lang.ArrayIndexOutOfBoundsException: 527
	at com.boydti.fawe.object.changeset.DiskStorageHistory$DiskStorageSummary.add(DiskStorageHistory.java:468) ~[?:?]
	at com.boydti.fawe.object.changeset.DiskStorageHistory.summarize(DiskStorageHistory.java:414) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommands.faweRollback(HistoryCommands.java:114) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:266) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommandOnCurrentThread$0(CommandManager.java:459) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:481) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:461) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.lambda$null$1(CommandManager.java:575) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:309) ~[?:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-620]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-620]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[01:22:57] [Server thread/INFO]: player issued server command: //frb #import player
[01:21:57] [Server thread/INFO]: player issued server command: //frb player 5 1d
```

https://paste.ubuntu.com/p/PK5vGp4WHr/

**Comment by mibby** [comment]
@boy0001 New error as of FAWE-Breaking dev 95.

```
[08:34:07] [Craft Scheduler Thread - 14/INFO]: WorldEdit: mibby (in "world"): /frb #import
[08:34:07] [Craft Scheduler Thread - 14/ERROR]: An unexpected error occurred while handling a FAWE command
java.lang.ArrayIndexOutOfBoundsException: 1019
	at com.sk89q.worldedit.world.block.BlockTypes.getFromStateId(BlockTypes.java:941) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockState.getFromInternalId(BlockState.java:75) ~[?:?]
	at com.boydti.fawe.object.changeset.DiskStorageHistory$DiskStorageSummary.add(DiskStorageHistory.java:471) ~[?:?]
	at com.boydti.fawe.object.changeset.DiskStorageHistory.summarize(DiskStorageHistory.java:417) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommands.faweRollback(HistoryCommands.java:114) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:266) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommandOnCurrentThread$0(CommandManager.java:459) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:481) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:461) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.lambda$null$1(CommandManager.java:575) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:309) ~[?:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-624]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by dextonanderson** [comment]
I think this is the same issue but whenever I try to perform a rollback, there are 0 changes found. Using the inspect tool, however, does show changes.
