### ISSUE TITLE
Schematic load from URL broken

### ISSUE THREAD

**Issue by Quicksteve** [IntellectualSites/FastAsyncWorldEdit-1.13#136]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
> fawe version
[12:19:55 INFO]: (FAWE) FAWE 19.4.19-e27b6fb-13 by Empire92
[12:19:55 INFO]: ------------------------------------
[12:19:55 INFO]:  - DATE: Apr 19, 2019 12:00:00 AM
[12:19:55 INFO]:  - COMMIT: e27b6fb
[12:19:55 INFO]:  - BUILD: #13
[12:19:55 INFO]:  - PLATFORM: bukkit
[12:19:55 INFO]: ------------------------------------
[12:19:55 INFO]: Platforms:
[12:19:55 INFO]:  - Bukkit (1.13.76)
[12:19:55 INFO]: Capabilities:
[12:19:55 INFO]:  - GAME_HOOKS: Bukkit
[12:19:55 INFO]:  - CONFIGURATION: Bukkit
[12:19:55 INFO]:  - USER_COMMANDS: Bukkit
[12:19:55 INFO]:  - PERMISSIONS: Bukkit
[12:19:55 INFO]:  - WORLDEDIT_CUI: Bukkit
[12:19:55 INFO]:  - WORLD_EDITING: Bukkit
[12:19:55 INFO]: ------------------------------------
[12:19:55 INFO]: Wiki: https://github.com/boy0001/FastAsyncWorldedit/wiki
```
**[REQUIRED] Spigot/Paper Version Number:** 

```
> version
[12:20:31 INFO]: This server is running Paper version git-Paper-621 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[12:20:31 INFO]: Previous version: git-Paper-439 (MC: 1.13.2)
[12:20:31 INFO]: Checking version, please wait...
[12:20:33 INFO]: You are 3 version(s) behind
```
**Links to config.yml and config-legacy.yml file:** 

config.yml: https://hastebin.com/moxetoxaha.coffeescript
config-legacy.yml: https://hastebin.com/uzuwibexap.pl
**[REQUIRED] Description of the problem:**

Loading schematic from url gives an error:
```
[12:12:19 INFO]: REDACTED issued server command: //schem load url:d171e806-2224-4ac9-8a39-eb541e21c101
[12:12:19 ERROR]: An unexpected error occurred while handling a FAWE command
java.lang.NullPointerException: null
        at com.sk89q.worldedit.command.SchematicCommands.load(SchematicCommands.java:224) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:266) ~[?:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[?:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommandOnCurrentThread$0(CommandManager.java:459) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:481) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:461) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.lambda$null$1(CommandManager.java:575) ~[?:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:309) ~[?:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-621]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-621]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-621]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
**Plugins being used on the server:**

FastAsyncVoxelSniper is also installed
**How to replicate**:

Uploaded a schematic, tried loading it from URL, didn't work.
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Try updating Fawe, it should be fixed in a new version https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/

**Comment by N0tMyFaultOG** [comment]
No response, assume fixed
