### ISSUE TITLE
Brush not working?

### ISSUE THREAD

**Issue by eryk172** [IntellectualSites/FastAsyncWorldEdit-1.13#144]
![image](https://user-images.githubusercontent.com/47436122/57588676-e64cc800-7517-11e9-992c-76d1766b2f2f.png)

```

[00:40:22] [Server thread/INFO]: Eryk172 issued server command: /brush smooth 8 4
[00:40:23] [Craft Scheduler Thread - 967/ERROR]: An unexpected error occurred while handling a FAWE command
java.lang.NullPointerException: null
	at com.boydti.fawe.util.BrushCache.setTool(BrushCache.java:80) ~[?:?]
	at com.sk89q.worldedit.LocalSession.setTool(LocalSession.java:1073) ~[?:?]
	at com.sk89q.worldedit.LocalSession.setTool(LocalSession.java:1058) ~[?:?]
	at com.sk89q.worldedit.command.BrushProcessor.process(BrushProcessor.java:34) ~[?:?]
	at com.sk89q.worldedit.command.BrushProcessor.process(BrushProcessor.java:19) ~[?:?]
	at com.sk89q.worldedit.util.command.ProcessedCallable.call(ProcessedCallable.java:22) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommandOnCurrentThread$0(CommandManager.java:459) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:481) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:461) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.lambda$null$1(CommandManager.java:575) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:309) ~[?:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-624]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-624]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by N0tMyFaultOG** [comment]
Follow the format given

**Comment by eryk172** [comment]
`/brush smooth 2 4`
and I have this error:
`java.lang.NullPointerException: null`
and
`/brush smooth 2 4 6`

`/brush smooth 2 4 2`
`/brush smooth 2 4 true`

Everything

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/e4c1ba3edf98a6ee19d8c36159b814808961c77d
