### ISSUE TITLE
"/searchitem" results in error depending on the material

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#15]
If i type /searchitem  stripped

(attempting to find the ID for stripped logs)

the following error occurs

https://pastebin.com/3WaXRsb7

/fawe version
outputs:  FAWE unknown by Empire92

IronApollo sent me the testing version of the vector update which is what i was using

CraftBukkit version git-Spigot-f56e2e7-0c715b3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT

**Comment by RealmportalMC** [comment]
@IronApollo

**Comment by AeSix** [comment]
This is still an issue with FAWE-NVS 165. 
```There was an error handling a FAWE command: [See console]
java.lang.NullPointerException: null```

```
[20:48:56 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NullPointerException: null
        at com.sk89q.worldedit.command.OptionsCommands.searchItem(OptionsCommands.java:303) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[?:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:331) ~[?:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-517]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-517]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-517]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```
https://incendo.org/paste/view/8f1a5635577e447b9aa49fdeab02bc25
