### ISSUE TITLE
/frb #import gives error

### ISSUE THREAD

**Issue by PixelNotFound** [IntellectualSites/FastAsyncWorldEdit-1.13#164]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

fawe version=> [16:21:16 INFO]: FastAsyncWorldEdit-1.13-117 by Empire92
[16:21:16 INFO]: ------------------------------------
[16:21:16 INFO]: - DATE: May 31, 2019 12:00:00 AM
[16:21:16 INFO]: - COMMIT: c73fc28
[16:21:16 INFO]: - BUILD: 117
[16:21:16 INFO]: - PLATFORM: bukkit
[16:21:16 INFO]: ------------------------------------
[16:21:16 INFO]: Platforms:
[16:21:16 INFO]: - Bukkit
[16:21:16 INFO]: Capabilities:
[16:21:16 INFO]: - GAME_HOOKS: Bukkit
[16:21:16 INFO]: - CONFIGURATION: Bukkit
[16:21:16 INFO]: - USER_COMMANDS: Bukkit
[16:21:16 INFO]: - PERMISSIONS: Bukkit
[16:21:16 INFO]: - WORLDEDIT_CUI: Bukkit
[16:21:16 INFO]: - WORLD_EDITING: Bukkit
[16:21:16 INFO]: ------------------------------------
[16:21:16 INFO]: Wiki: https://github.com/boy0001/FastAsyncWorldedit/wiki
**[REQUIRED] Spigot/Paper Version Number:** 

version=> [16:21:31 INFO]: This server is running Paper version git-Paper-629 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:21:31 INFO]: Previous version: git-Paper-628 (MC: 1.13.2)
[16:21:31 INFO]: Checking version, please wait...
[16:21:32 INFO]: You are running the latest version
**Links to config.yml and config-legacy.yml file:** 

**[REQUIRED] Description of the problem:**

When i do /frb #import i get a error

`> [16:19:08 ERROR]: An unexpected error occurred while handling a FAWE command
java.lang.ArrayIndexOutOfBoundsException: 1023
at com.sk89q.worldedit.world.block.BlockTypes.getFromStateId(BlockTypes.java:941) ~[?:?]
at com.sk89q.worldedit.world.block.BlockState.getFromInternalId(BlockState.java:75) ~[?:?]
at com.boydti.fawe.object.changeset.DiskStorageHistory$DiskStorageSummary.add(DiskStorageHistory.java:471) ~[?:?]
at com.boydti.fawe.object.changeset.DiskStorageHistory.summarize(DiskStorageHistory.java:417) ~[?:?]
at com.sk89q.worldedit.command.HistoryCommands.faweRollback(HistoryCommands.java:114) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:266) ~[?:?]
at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[?:?]
at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommandOnCurrentThread$0(CommandManager.java:459) ~[?:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:481) ~[?:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:461) ~[?:?]
at com.sk89q.worldedit.extension.platform.CommandManager.lambda$null$1(CommandManager.java:575) ~[?:?]
at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:309) ~[?:?]
at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-629]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-629]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-629]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]`
**Plugins being used on the server:**

**How to replicate**:

Do /frb #import
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by PixelNotFound** [comment]
Issue still persists on Build #126 latest availible.
