### ISSUE TITLE
[PS] plot download not work with fawe

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/FastAsyncWorldEdit-1.13#206]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] Spigot/Paper Version Number:** 
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
**Links to config.yml and config-legacy.yml file:** 
**Plugins being used on the server:**
All here : https://athion.net/ISPaster/paste/view/30ab996ce15e425ba8bb5a1398ca07a6

**[REQUIRED] Description of the problem:**
With plotsquared, the plot download make a exception into FAWE
```
[02:12:42] [Craft Scheduler Thread - 4/WARN]: [PlotSquared] Plugin PlotSquared v4.309 generated an exception while executing task 327
java.lang.IllegalArgumentException: Invalid tag classs (com.sk89q.jnbt.CompressedSchematicTag).
	at com.sk89q.jnbt.NBTUtils.getTypeCode(NBTUtils.java:116) ~[?:?]
	at com.sk89q.jnbt.NBTOutputStream.writeNamedTag(NBTOutputStream.java:92) ~[?:?]
	at com.boydti.fawe.regions.general.plot.FaweSchematicHandler$1.run(FaweSchematicHandler.java:129) ~[?:?]
	at com.boydti.fawe.regions.general.plot.FaweSchematicHandler$1.run(FaweSchematicHandler.java:121) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.MainUtil.lambda$upload$0(MainUtil.java:153) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-641]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-641]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-641]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```
Issue reference for Plotsquared
https://github.com/IntellectualSites/PlotSquared/issues/2363

![image](https://user-images.githubusercontent.com/472429/62666304-268add80-b983-11e9-8a63-d77208e4d56f.png)

**How to replicate**:
- PlotSquared/FAWE installed
- /plot download on one plot

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by jewome62** [comment]
I confirm that's work with regular WorldEdit but not FAWE

**Comment by jewome62** [comment]
Hello @N0tMyFaultOG 

I have test with latest build of plotsquared and FAWE.
That's work well i try download and load

But, i can't use this release for another problem :S 
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/251
