### ISSUE TITLE
Bug with FAWE 1.14.4#33 //copy //flip up //paste

### ISSUE THREAD

**Issue by TheCalypso** [IntellectualSites/FastAsyncWorldEdit-1.13#213]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

fawe version
[18:55:22] [Craft Scheduler Thread - 1/WARN]: [WorldEdit] Plugin WorldEdit v1.14-33 generated an exception while executing task 7
java.lang.NullPointerException: null
        at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommand$1(CommandManager.java:537) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[paper.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [paper.jar:git-Spigot-ea7e48b-368f4e9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

It's my plugins folder !

![image](https://user-images.githubusercontent.com/33781244/63640461-ef197200-c6a0-11e9-99f9-cba8a78720da.png)

**[REQUIRED] Spigot/Paper Version Number:** 

[18:54:27] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-ea7e48b-368f4e9 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[18:54:27] [Server thread/INFO]: Checking version, please wait...
[18:54:28] [Thread-9/INFO]: You are 8 version(s) behind

But it's same with PaperSpigot lastedbuild :(

**Links to config.yml and config-legacy.yml file:** 

It's default config :) I change nothing

**[REQUIRED] Description of the problem:**

I use:
//pos1
//pos2
//copy
//flip up
//paste
and nothing happens :(

https://pastebin.com/VRYR5X4D
It's my logs server
**Plugins being used on the server:**

**How to replicate**:

**Checklist**:

- [] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
We will not be taking issues on the 1.14.4 snapshot build.

**Comment by TheCalypso** [comment]
Hello,
What is the use of making devbuild available for all if we can not even report bugs?

**Comment by MattBDev** [comment]
@TheCalypso It's not a dev build, it's a snapshot. We made it so we could stop hearing "How much longer until FAWE for 1.14?" all day long. All we did was change 1.13 to 1.14 in one file and a few other small changes. We literally put no effort into it.

**Comment by TheCalypso** [comment]
Owh I see, we wait a bit then the time that a real version out 😅, finally if there is one. Good luck to you !
