### ISSUE TITLE
Schematic paste problem

### ISSUE THREAD

**Issue by Gnaciko** [IntellectualSites/FastAsyncWorldEdit-1.13#247]
Tested on Spigot 1.14.4 and FAWE dev build 1.14-82

Using old code to paste schematic, works with old versions of FAWE:

`
		BlockVector3 loc = BlockVector3.at(x, y, z);
		
		EditSession editSession = null;
		try {
			editSession = ClipboardFormats.findByFile(schemaFile).load(schemaFile).paste(BukkitAdapter.adapt(world), loc, false, false, (Transform) null);
		} catch (IOException e) {
			e.printStackTrace();
		}

		editSession.flushQueue();
`

after updating spigot and fawe to 1.14 it drops error:

`
[19:06:36] [Server thread/WARN]: [IslandWorld] Task #34 for IslandWorld v14.5 generated an exception
java.lang.ArrayIndexOutOfBoundsException: -1
        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.set(CharBlocks.java:116) ~[?:?]
        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.set(CharBlocks.java:104) ~[?:?]
        at com.boydti.fawe.beta.implementation.blocks.CharSetBlocks.setBlock(CharSetBlocks.java:83) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$3.setBlock(ChunkHolder.java:207) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.setBlock(ChunkHolder.java:464) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$4.setBlock(ChunkHolder.java:260) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.setBlock(ChunkHolder.java:464) ~[?:?]
        at com.boydti.fawe.beta.implementation.IChunkExtent.setBlock(IChunkExtent.java:25) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:189) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:878) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.paste(Clipboard.java:348) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.paste(Clipboard.java:274) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.paste(Clipboard.java:240) ~[?:?]
        at pl.islandworld.managers.FAWESchematicManager.pasteSchematic(FAWESchematicManager.java:68) ~[?:?]
        at pl.islandworld.IslandWorld$pasteIsland.run(IslandWorld.java:1323) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [spigot-1.14.4.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-56f8471-56118c6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
`

FAWESchematicManager.java:68 is ClipboardFormats.... line

**Comment by MattBDev** [comment]
@Gnaciko Other plugins that used the FAWE API will likely break in 1.14.4
I'll have to look into this further though to make sure it isn't just an API issue

**Comment by boy0001** [comment]
Want to attach the schematic you are trying to paste?

**Comment by Gnaciko** [comment]
yes, i think problem is inside fawe not api itself. Since same code is working without problems with old FAWE version. 

Schematic is also correct, its not a reason - same schematic is working with old FAWE version, with AsyncWE and clear WorldEdit.

**Comment by stuvanya** [comment]
I have similar error:

Hello! I'm using last dev build for 1.14 and have this error while pasting schematic:
https://pastebin.com/J8Gscfa3
My code:
https://pastebin.com/ECgDevU0

**Comment by Pet0203** [comment]
Also have this problem, doesn not occur on normal WE/AWE.
