### ISSUE TITLE
Incompatibility with Plotsquared

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/FastAsyncWorldEdit-1.13#251]
Hello,

Current version of FAWE is non compatible with PlotSquared version 4.400 (lastest release)

The cause is Plotsquared use now `CuboidSelection` (From WorldEdit class) insteadof `RegionWrapper` 
And `getRegion` from `Plot` return the interface `Set` and not the implementation `HashSet`

the code in question here : 
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/blob/c1a0819acb2ab73615bbb05f8c81c248f736fd33/worldedit-core/src/main/java/com/boydti/fawe/regions/general/plot/PlotSquaredFeature.java#L103

Exception
```
[22:18:08] [Server thread/WARN]: java.lang.NoSuchMethodError: com.github.intellectualsites.plotsquared.plot.object.Plot.getRegions()Ljava/util/HashSet;
[22:18:08] [Server thread/WARN]: 	at com.boydti.fawe.regions.general.plot.PlotSquaredFeature.getMask(PlotSquaredFeature.java:106)
[22:18:08] [Server thread/WARN]: 	at com.boydti.fawe.util.WEManager.getMask(WEManager.java:136)
[22:18:08] [Server thread/WARN]: 	at com.boydti.fawe.util.WEManager.getMask(WEManager.java:72)
[22:18:08] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.getCurrentRegions(FawePlayer.java:544)
[22:18:08] [Server thread/WARN]: 	at com.sk89q.worldedit.EditSession.<init>(EditSession.java:371)
[22:18:08] [Server thread/WARN]: 	at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:194)
[22:18:08] [Server thread/WARN]: 	at com.boydti.fawe.object.FawePlayer.getNewEditSession(FawePlayer.java:643)
[22:18:08] [Server thread/WARN]: 	at gc.arcaniax.gobrush.listener.PlayerInteractListener.onClickEvent(PlayerInteractListener.java:39)
[22:18:08] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor160.execute(Unknown Source)
[22:18:08] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[22:18:08] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[22:18:08] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[22:18:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[22:18:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1348)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[22:18:08] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:18:08] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[22:18:08] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[22:18:08] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
Details
https://athion.net/ISPaster/paste/view/b2e2dce8090b4c769186190c38598d69

**Comment by jewome62** [comment]
The consequence on the game is FAWE don't work for nobody on their plots, because it not reconize the owner or members
That's work if admin and `/wea` enabled

**Comment by MattBDev** [comment]
Please don't delete the issue template. It has information we need. The current version of PlotSquared is 4.440
Generate a debugpaste in game and provide it here. Otherwise I'll have to close this issue.

**Comment by MattBDev** [comment]
Nevermind I found the debug paste. You are still using an outdated PlotSquared version.

**Comment by jewome62** [comment]
@MattBDev 

On debug paste, the version mentionned is 4.400
![image](https://user-images.githubusercontent.com/472429/69013297-ce4e7900-097e-11ea-88d9-0cdfe7e4e21d.png)
And you said : `The current version of PlotSquared is 4.440`

And in all case, the problems still same
Définition : `Plot.getRegion()` return `Set<CuboidRegion>`
https://github.com/IntellectualSites/PlotSquared/blob/10e5760ba8b7d3c49d7a093533350864269541e0/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/Plot.java#L2604

Usage into FAWE `Plot.getRegion()` is save into `HashSet<RegionWrapper>`
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/blob/c1a0819acb2ab73615bbb05f8c81c248f736fd33/worldedit-core/src/main/java/com/boydti/fawe/regions/general/plot/PlotSquaredFeature.java#L103

There will remain exceptions and it will not work until the use of the method will respect the interface

**Comment by boy0001** [comment]
The pipeline builds of FAWE (which are compatible with P2) are only for 1.14 right now.
