### ISSUE TITLE
Exception when attempting to undo schematic paste

### ISSUE THREAD

**Issue by A-Chicken-Nugget** [IntellectualSites/FastAsyncWorldEdit-1.13#273]
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/67066a08cee842deb77dc5927a2c7bc0

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
latest so FastAsyncWorldEdit-1.14-145

**[REQUIRED] Spigot/Paper Version Number:** 
Spigot 1.14.4

**[REQUIRED] Description of the problem:**
I am attempting to undo a schematic paste pasted using FAWE. I have followed the example [here ](https://github.com/boy0001/FastAsyncWorldedit/wiki/WorldEdit-EditSession) on how to undo an editsession.

Heres my code:

_Pasting a schematic_
`EditSession test = ClipboardFormats.findByFile(schem).load(schem).paste(new BukkitWorld(Bukkit.getWorld("games_world")), BlockVector3.at((gamePos.x*500)-(500/2), 200, (gamePos.y*500)-(500/2)), false, false, (Transform) null);`
`game.setEditSession(test); //This is used to save this edit session and associate it with the current game its being used for.`

_Undoing the pasted schematic_
`EditSession editSession = game.getEditSession(); //Gets the editsession associated with this game`
`EditSession test = WorldEdit.getInstance().getEditSessionFactory().getEditSession(editSession.getWorld(), -1, null, null);`
`editSession.undo(test);`
`editSession.flushQueue();`

Here is the exception being thrown as soon as I attempt to undo the editsession:

`Could not pass event PlayerInteractEvent to ServerCoreTest v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:437) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:404) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:400) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	at com.sk89q.worldedit.function.operation.ChangeSetExecutor.<init>(ChangeSetExecutor.java:68) ~[?:?]
	at com.sk89q.worldedit.function.operation.ChangeSetExecutor.create(ChangeSetExecutor.java:97) ~[?:?]
	at com.sk89q.worldedit.EditSession.undo(EditSession.java:942) ~[?:?]
	at nyeblock.Core.ServerCoreTest.PlayerHandling.onPlayerUse(PlayerHandling.java:893) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
	... 20 more`

Now the undo is being done here "nyeblock.Core.ServerCoreTest.PlayerHandling.onPlayerUse(PlayerHandling.java:893)" and the line its referring to is the .undo method call. I have checked all of the variables being used and none of them are null. So i'm assuming there is something going wrong internally in FAWE.

**Comment by N0tMyFaultOG** [comment]
That wiki is outdated, any advice for 1.13+ is documented here: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
If you want help regarding the api, just visit us on discord.
