### ISSUE TITLE
griefprevention bug

### ISSUE THREAD

**Issue by spmscgalaxy8970** [IntellectualSites/FastAsyncWorldEdit-1.13#290]
[19:01:18 INFO]: _Rumino_ issued server command: //set 0
[19:01:18 INFO]: TODO add progress display
[19:01:18 INFO]: TODO FIXME TIPS
[19:01:18 WARN]: java.lang.ArrayIndexOutOfBoundsException: -1
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.hasSection(CharBlocks.java:85)
[19:01:18 WARN]:        at com.boydti.fawe.beta.IBatchProcessor.trimY(IBatchProcessor.java:72)
[19:01:18 WARN]:        at com.sk89q.worldedit.regions.CuboidRegion.processSet(CuboidRegion.java:728)
[19:01:18 WARN]:        at com.boydti.fawe.object.extent.SingleRegionExtent.processSet(SingleRegionExtent.java:44)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.LimitProcessor.processSet(LimitProcessor.java:22)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:60)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:19)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:19)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:419)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:410)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:29)
[19:01:18 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:01:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:01:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:01:18 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:01:18 WARN]: java.lang.ArrayIndexOutOfBoundsException: -1
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.hasSection(CharBlocks.java:85)
[19:01:18 WARN]:        at com.boydti.fawe.beta.IBatchProcessor.trimY(IBatchProcessor.java:72)
[19:01:18 WARN]:        at com.sk89q.worldedit.regions.CuboidRegion.processSet(CuboidRegion.java:728)
[19:01:18 WARN]:        at com.boydti.fawe.object.extent.SingleRegionExtent.processSet(SingleRegionExtent.java:44)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.LimitProcessor.processSet(LimitProcessor.java:22)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:60)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:19)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:19)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:419)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:410)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:29)
[19:01:18 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:01:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:01:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:01:18 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:01:18 WARN]: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
[19:01:18 WARN]:        at java.util.concurrent.FutureTask.report(Unknown Source)
[19:01:18 WARN]:        at java.util.concurrent.FutureTask.get(Unknown Source)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:265)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.queue.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:319)
[19:01:18 WARN]:        at com.boydti.fawe.beta.IQueueExtent.commit(IQueueExtent.java:107)
[19:01:18 WARN]:        at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:231)
[19:01:18 WARN]:        at com.sk89q.worldedit.extent.PassthroughExtent.commit(PassthroughExtent.java:231)
[19:01:18 WARN]:        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1001)
[19:01:18 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:736)
[19:01:18 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:675)
[19:01:18 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$15(PlatformCommandManager.java:645)
[19:01:18 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[19:01:18 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:01:18 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:01:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:01:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:01:18 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:01:18 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.hasSection(CharBlocks.java:85)
[19:01:18 WARN]:        at com.boydti.fawe.beta.IBatchProcessor.trimY(IBatchProcessor.java:72)
[19:01:18 WARN]:        at com.sk89q.worldedit.regions.CuboidRegion.processSet(CuboidRegion.java:728)
[19:01:18 WARN]:        at com.boydti.fawe.object.extent.SingleRegionExtent.processSet(SingleRegionExtent.java:44)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.LimitProcessor.processSet(LimitProcessor.java:22)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:60)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:19)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:19)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:419)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:410)
[19:01:18 WARN]:        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:29)
[19:01:18 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:01:18 WARN]:        ... 3 more

I think    fawe.griefprevention   <- doesn't work

with region-restrictions: true   -> it works fine

**Comment by N0tMyFaultOG** [comment]
Don't delete the template
