### ISSUE TITLE
//cancel causes Null pointer exception when cancelling //undo

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#30]
I type //undo and whilte its undoing i did //cancel
the following error occured and my actions were not canceled
```
[19:48:15 WARN]: java.lang.NullPointerException
[19:48:15 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:510)
[19:48:15 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$EntryIterator.next(Long2ObjectOpenHashMap.java:574)
[19:48:15 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$EntryIterator.next(Long2ObjectOpenHashMap.java:571)
[19:48:15 WARN]:        at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:132)
[19:48:15 WARN]:        at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:211)
[19:48:15 WARN]:        at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[19:48:15 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[19:48:15 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[19:48:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[19:48:15 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[19:48:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[19:48:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[19:48:15 WARN]:        at java.lang.Thread.run(Unknown Source)
```

Using @IronApollo vector update

**Comment by AeSix** [comment]
Confirmed to be an issue with FAWE-NVS 165:
Cancel throws npe when setting and undoing.
```
[21:58:09 INFO]: AeSix_Reficul issued server command: //set stone
[21:58:13 INFO]: AeSix_Reficul issued server command: //cancel
[21:58:13 WARN]: java.lang.NullPointerException
[21:58:13 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:669)
[21:58:13 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$EntryIterator.next(Long2ObjectOpenHashMap.java:743)
[21:58:13 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$EntryIterator.next(Long2ObjectOpenHashMap.java:739)
[21:58:13 WARN]:        at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:132)
[21:58:13 WARN]:        at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:211)
[21:58:13 WARN]:        at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[21:58:13 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[21:58:13 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[21:58:13 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[21:58:13 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:58:13 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[21:58:13 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[21:58:13 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

```
[21:58:34 INFO]: AeSix_Reficul issued server command: //undo
[21:58:35 INFO]: AeSix_Reficul issued server command: //cancel
[21:58:35 WARN]: java.lang.NullPointerException
[21:58:35 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:669)
[21:58:35 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$EntryIterator.next(Long2ObjectOpenHashMap.java:743)
[21:58:35 WARN]:        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$EntryIterator.next(Long2ObjectOpenHashMap.java:739)
[21:58:35 WARN]:        at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:132)
[21:58:35 WARN]:        at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:211)
[21:58:35 WARN]:        at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[21:58:35 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[21:58:35 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[21:58:35 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[21:58:35 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:58:35 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[21:58:35 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[21:58:35 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by N0tMyFaultOG** [comment]
Still an issue in latest fawe-breaking
