### ISSUE TITLE
NoSuchMethodError: com.sk89q.worldedit.EditSession.flushSession()V

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#48]
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2
https://github.com/slipcor/pvparena_modules/tree/1.13/m_WorldEdit

Found a plugin incompatibility with FAWE 1.13. Plugin module works perfectly fine with WorldEdit dev 4048. Thought I read that the new intent is for FAWE to be upstream compatible with WE 1.13 so plugin compatibility can remain, so figured I'd forward this to you. :)
```
[22:17:29] [Server thread/WARN]: [PVP Arena] Task #297585 for pvparena v1.13.5 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldedit.EditSession.flushSession()V
	at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:289) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:257) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.reset(PAWE.java:344) ~[?:?]
	at net.slipcor.pvparena.loadables.ArenaModuleManager.reset(ArenaModuleManager.java:266) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1455) ~[?:?]
	at net.slipcor.pvparena.runnables.EndRunnable.commit(EndRunnable.java:53) ~[?:?]
	at net.slipcor.pvparena.runnables.ArenaRunnable.run(ArenaRunnable.java:161) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by IronApollo** [comment]
Fixed in 0fa9d7a4a7a90160fc351a46a1f65fb44b98ecc8. Closed.
