### ISSUE TITLE
IllegalArgumentException: Cannot drop air // Unable to parse CustomName on schematic paste.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#49]
Paper dev 525 (Spigot 1.13.2)
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2

https://paste.ubuntu.com/p/RcSGzJgmwq/

```
[22:35:37] [Server thread/WARN]: net.minecraft.server.v1_13_R2.ReportedException: Loading entity NBT
[22:35:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Entity.f(Entity.java:1850)
[22:35:37] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.readTagIntoEntity(Spigot_v1_13_R2.java:173)
[22:35:37] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.createEntity(Spigot_v1_13_R2.java:345)
[22:35:37] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v0.BukkitChunk_All.call(BukkitChunk_All.java:148)
[22:35:37] [Server thread/WARN]: 	at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:138)
[22:35:37] [Server thread/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:211)
[22:35:37] [Server thread/WARN]: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[22:35:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[22:35:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[22:35:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[22:35:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:35:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[22:35:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[22:35:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:35:37] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Cannot drop air
[22:35:37] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[22:35:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityItem.setItemStack(EntityItem.java:409)
[22:35:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityItem.a(EntityItem.java:300)
[22:35:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Entity.f(Entity.java:1769)
[22:35:37] [Server thread/WARN]: 	... 13 more
```

**Comment by AeSix** [comment]
@mibby is this still an issue?
I've not seen this at all in my logs.  I'm not sure how to replicate the issue as you did not tell us. 
If the issue continues, please provide:
situation
replication
debugpaste

If it is not longer an issue, please let us know, and close the ticket.  Thank you! :)

**Comment by mibby** [comment]
@AeSix As far as I'm aware, it is. Due to some breaking issues with plugin incompatibility and schematic pasting (off-set/not preserving NBT data in schematics), I've temporarily gone back to vanilla worldedit for the time being.

I'll be able to re-test in a couple of days if someone else doesn't take care of it first. As this was gathered from reviewing logs for errors upon mass worldedit user testing, I'll need to test schematic pasting of entities / nbt again in a similar environment / clipboard.

Try loading the same schematic used if it happens to still be active on the FAWE remote upload/download server.
```
//schematic load url:d6f5d8f5-b25e-414d-9fd9-6f3055107a96
```

**Comment by AeSix** [comment]
Great! Thank you for the info. 
Unfortunately, the last build I have, schematics are still broken, as are NBT datum.

**Comment by mibby** [comment]
Paper dev 584 (Spigot 1.13.2)

Re-tested as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e (compiled 03/25) loading the same schematic used ``//schematic load url:d6f5d8f5-b25e-414d-9fd9-6f3055107a96``.

The error still occurs.
https://paste.ubuntu.com/p/cGKz2wvn5m/

I also noticed issues with chunks being skipped, leaving holes;
![link2](https://i.imgur.com/Evj5KRG.jpg)
![link3](https://i.imgur.com/EfnJHeC.jpg)

Signs having broken data;
![link4](https://i.imgur.com/BxhG6O8.jpg)

And it not fully cleaning up all blocks on undo;
![link5](https://i.imgur.com/F0Titmr.jpg)
