### ISSUE TITLE
IllegalArgumentException: minY <= maxY required

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#54]
Paper dev 525 (Spigot 1.13.2)
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2

```
[06:58:36] [Server thread/INFO]: player issued server command: //fill dirt 10
[06:58:36] [Craft Scheduler Thread - 742/INFO]: WorldEdit: player (in "creative"): /fill dirt 10 - Position: (-830.0, 64.0, 514.0)
[06:58:36] [Craft Scheduler Thread - 742/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.IllegalArgumentException: minY <= maxY required
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-525]
	at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[?:?]
	at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1476) ~[?:?]
	at com.sk89q.worldedit.EditSession.fillDirection(EditSession.java:1425) ~[?:?]
	at com.sk89q.worldedit.command.UtilityCommands.fill(UtilityCommands.java:275) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:331) ~[?:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-525]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-525]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by SirYwell** [comment]
I can reproduce this for y coordinates > 256 and < 0, but it seems like you were standing on a valid position. Can you still reproduce it?

**Comment by Sauilitired** [comment]
Can't reproduce this anywhere within the valid range (0, 256), using the latest build of the new-vector-system branch.

The check is done in BoundedHeightMask, using this:
```java
new BoundedHeightMask(Math.max(
                (origin.getBlockY() - depth) + 1, getMinimumPoint().getBlockY()), Math.min(getMaximumPoint().getBlockY(), origin.getBlockY()))
```

where the origin is the player position. The maximum and minimum points either either 0 and 255, or set by the extent. 

A way to circumvent this is by using `/toggleplace`, set the position outside of the normal boundaries and then moving inside of the boundaries, then using `//fill`, but even by doing so it will be clamped to the maximum and minimum extent positions.

**Comment by mibby** [comment]
I'll see if I can reproduce in a couple of days if someone else doesn't get to it before me, but I didn't see any substantial commit changes to the vector branch that would indicate this being fixed. 

I'm also not too sure _how_ to reproduce, as this was gathered from reviewing logs for errors upon mass worldedit user testing.

**Comment by mibby** [comment]
@IronApollo @Sauilitired 

Tested as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e, this still occurs.

I _believe_ it may be due to PlotSquared / FAWE's ```region-restrictions: true``` setting.
![link](https://i.imgur.com/jQvwLYk.png)

I teleported to my creative world, went to the same coordinates (which were on a plot border), typed the command ``/fill dirt 10``, and the error occurred. 

```
[18:55:56] [Server thread/INFO]: mibby issued server command: /tppos -830 64 514
[18:56:02] [Server thread/INFO]: mibby issued server command: //fill dirt 10
[18:56:02] [Craft Scheduler Thread - 70/INFO]: WorldEdit: mibby (in "creative"): /fill dirt 10 - Position: (-830.0, 66.0, 514.0)
[18:56:02] [Craft Scheduler Thread - 70/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.IllegalArgumentException: minY <= maxY required
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-584]
	at com.sk89q.worldedit.function.mask.BoundedHeightMask.<init>(BoundedHeightMask.java:44) ~[?:?]
	at com.sk89q.worldedit.EditSession.fillXZ(EditSession.java:1451) ~[?:?]
	at com.sk89q.worldedit.EditSession.fillDirection(EditSession.java:1400) ~[?:?]
	at com.sk89q.worldedit.command.UtilityCommands.fill(UtilityCommands.java:275) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:331) ~[?:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-584]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-584]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-584]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[18:56:45] [Server thread/INFO]: mibby issued server command: /plot wea
[18:56:46] [Server thread/INFO]: mibby issued server command: //fill dirt 10
[18:56:47] [Craft Scheduler Thread - 74/INFO]: WorldEdit: mibby  (in "creative"): /fill dirt 10 - Position: (-830.0, 66.0, 514.0)
```

Bypassing with ``/plot wea``, I am able to type the worldedit command fine with the exception that it bypasses plot region edit restrictions (as intended).

**Comment by SirYwell** [comment]
I was able to reproduce it as you described. Thank you for investigating.

**Comment by lusu007** [comment]
Ran into the same issue today.

Debugpaste: https://athion.net/ISPaster/paste/view/74e8cc897c904ed1a9a6c53b9a2751ac
