### ISSUE TITLE
NullPointerException - VoxelVoxelCommand.onCommand

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#55]
Paper dev 525 (Spigot 1.13.2)
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2
FAVS 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2

```
[16:46:03] [Server thread/INFO]: playerissued server command: /v
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: java.lang.NullPointerException
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at com.thevoxelbox.voxelsniper.command.VoxelVoxelCommand.onCommand(VoxelVoxelCommand.java:55)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at com.thevoxelbox.voxelsniper.VoxelSniperListener$1.run(VoxelSniperListener.java:88)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:331)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:46:03] [Craft Scheduler Thread - 1569/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mibby** [comment]
@IronApollo Tested as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e, ``/v`` does not seem to error. Assuming fixed.
