### ISSUE TITLE
NullPointerException - DiskOptimizedClipboard.setBlock

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#56]
Paper dev 525 (Spigot 1.13.2)
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2

Possibly related to https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/pull/35 not being pulled into the 1.13 branch?

RE: https://github.com/NLthijs48/AreaShop/issues/482

```
[15:51:36] [Server thread/INFO]: player issued server command: /as unrent
[15:51:36] [Server thread/WARN]: java.lang.NullPointerException
[15:51:36] [Server thread/WARN]: 	at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.setBlock(DiskOptimizedClipboard.java:528)
[15:51:36] [Server thread/WARN]: 	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.readVersion1(SpongeSchematicReader.java:438)
[15:51:36] [Server thread/WARN]: 	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:109)
[15:51:36] [Server thread/WARN]: 	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:104)
[15:51:36] [Server thread/WARN]: 	at me.wiefferink.areashop.handlers.FastAsyncWorldEditHandler.restoreRegionBlocks(FastAsyncWorldEditHandler.java:102)
[15:51:36] [Server thread/WARN]: 	at me.wiefferink.areashop.regions.GeneralRegion.restoreRegionBlocks(GeneralRegion.java:794)
[15:51:36] [Server thread/WARN]: 	at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1432)
[15:51:36] [Server thread/WARN]: 	at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:694)
[15:51:36] [Server thread/WARN]: 	at me.wiefferink.areashop.commands.UnrentCommand.execute(UnrentCommand.java:79)
[15:51:36] [Server thread/WARN]: 	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:144)
[15:51:36] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:51:36] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[15:51:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[15:51:36] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:51:36] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[15:51:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[15:51:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mibby** [comment]
@IronApollo Compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/0fa9d7a4a7a90160fc351a46a1f65fb44b98ecc8 and re-compiled AreaShops with just vanilla WorldEdit dependencies without the FAWE detection.

I'm pretty confident that this error is caused by the SpongeSchematicReader being unfinished / more than half commented out. https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/blob/new-vector-system/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SpongeSchematicReader.java

I tried uncommenting the file but unfortunately ran into compilation errors. If this issue could be fixed, I'd be able to put FAWE back on my production environment for further testing. Compatibility with plugins (one of which was fixed with this commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/0fa9d7a4a7a90160fc351a46a1f65fb44b98ecc8) is the only thing really holding me back from continued testing.

**Comment by IronApollo** [comment]
I'm interested in seeing if this issue persists in https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/c98a31114681caf8c38eae64e112dcee7e512831.

**Comment by mibby** [comment]
@IronApollo Apologies for the delay, finally got around to testing this commit. 

This does seem to resolve the error, however the schematic rollback seems to be misaligned.

Before (unrented plot)
![link1](https://i.imgur.com/lb68Soi.jpg)

After (rented plot, then subsequently unrented again)
![link2](https://i.imgur.com/2tdpKke.jpg)

The plot is suppose to revert back to the before image when the rollback occurs. With vanilla worldedit dev 4106, all seems fine.

**Comment by mibby** [comment]
@IronApollo Seems to be fixed as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e - compiled 03/25. Renting, making minor changes, and unrenting, the plot schematic is pasted properly and not misaligned.

AreaShops will need to fix compatibility in their branch for FAWE, but with me simply removing their FAWE module and using just the latest WorldEdit one, it seems to work fine.
