### ISSUE TITLE
Server crash after replacing soulsand underwater / FAWE tick limiter causing crash - NoSuchElementException: null

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#57]
Paper dev 525 (Spigot 1.13.2)
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2

Server crash reported to me with FAWE after replacing soul sand underwater. 

> Bug with FAWE and soulsand
If you remove underwater soulsand with WE then give that block a blockupdate. The server dies and the client dies
But not every time It seems. not certain what was different the last time I did it. but it crashed the first 2 times and not the 3rd

```
[15:58:00] [Server thread/INFO]: (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics  lag source at Location{world=CraftWorld{name=world},x=-6009.0,y=54.0,z=-4395.0,pitch=0.0,yaw=0.0}
[15:58:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Exception ticking world
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1094) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327) ~[?:1.8.0_202]
	at java.util.TreeMap.firstKey(TreeMap.java:290) ~[?:1.8.0_202]
	at java.util.TreeSet.first(TreeSet.java:394) ~[?:1.8.0_202]
	at org.bukkit.craftbukkit.v1_13_R2.util.HashTreeSet.first(HashTreeSet.java:114) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:62) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:657) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:296) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1083) ~[patched_1.13.2.jar:git-Paper-525]
	... 4 more
[15:58:00] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.NoSuchElementException: null
	at java.util.TreeMap.key(TreeMap.java:1327) ~[?:1.8.0_202]
	at java.util.TreeMap.firstKey(TreeMap.java:290) ~[?:1.8.0_202]
	at java.util.TreeSet.first(TreeSet.java:394) ~[?:1.8.0_202]
	at org.bukkit.craftbukkit.v1_13_R2.util.HashTreeSet.first(HashTreeSet.java:114) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:62) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:657) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:296) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1083) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[15:58:00] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2019-02-20_15.58.00-server.txt
```

```
[15:59:37] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Exception ticking world
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1094) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327) ~[?:1.8.0_202]
	at java.util.TreeMap.firstKey(TreeMap.java:290) ~[?:1.8.0_202]
	at java.util.TreeSet.first(TreeSet.java:394) ~[?:1.8.0_202]
	at org.bukkit.craftbukkit.v1_13_R2.util.HashTreeSet.first(HashTreeSet.java:114) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:62) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:657) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:296) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1083) ~[patched_1.13.2.jar:git-Paper-525]
	... 4 more
[15:59:37] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.NoSuchElementException: null
	at java.util.TreeMap.key(TreeMap.java:1327) ~[?:1.8.0_202]
	at java.util.TreeMap.firstKey(TreeMap.java:290) ~[?:1.8.0_202]
	at java.util.TreeSet.first(TreeSet.java:394) ~[?:1.8.0_202]
	at org.bukkit.craftbukkit.v1_13_R2.util.HashTreeSet.first(HashTreeSet.java:114) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:62) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:657) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:296) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1083) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[15:59:37] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2019-02-20_15.59.37-server.txt
```

Crash log 1
https://paste.ubuntu.com/p/hFZYQjp43F/
Crash log 2
https://paste.ubuntu.com/p/kr4qTGPNX3/

**Comment by AeSix** [comment]
Using FAWE-NVS 165  this no longer *seems* to be an issue, however more testing may be required as the original reporter stated it did not always result in a crash.

**Comment by Sauilitired** [comment]
I dived into some NMS, just to flash my fancy decompiler that I know Iron doesn't have.

There are two important fields in that class, nextTickList which is a TreeSet (the one throwing the exception) and g, which is a list of... next tick list entries. 

This exception is thrown when attempting to fetch the next entry from nextTickList, when it doesn't exist. This method is called in a loop, going from zero to i, where i calculated using:

```java
int i = this.nextTickList.size();
if (i > 65536) {
  if (i > 1310720) {
    i /= 20;
  } else {
    i = 65536;
  }
}
```

so there's clearly something unusual with the nextTickList size, at the time of the crashes.

**Comment by AeSix** [comment]
I suggest testing in both Spigot and Paper, and to make sure to use default configs for the server pertaining to ticks/timing.  Paper handles ticks a little different, I believe, and may have different results than Spigot.

**Comment by mibby** [comment]
Unfortunately I will not be able to re-test this issue myself as I do not use, rely on, or need the tick-limiter since it affects plugins and server operations outside of worldedit. It may be worth looking into though if it is still causing server related freezes and crashing.
