### ISSUE TITLE
Incompatible with plugins using the WorldEdit 7 vector API

### ISSUE THREAD

**Issue by Phoenix616** [IntellectualSites/FastAsyncWorldEdit-1.13#62]
**Debug paste link**:
No output, throws the following error: https://gist.github.com/8173ec41f7e13832fcfdd19bd049632d

**Description of the problem:**
Due to not including the [WorldEdit 7 vector API](https://github.com/EngineHub/WorldEdit/commit/399e0ad5fa7637d5d3ccce7ead1ad409e85c7dd2) any plugin that depends on WorldEdit 7 and uses that part will fail to work.

**How to replicate**:
Use any plugin that uses the WE7 vector API e.g. to query WorldGuard regions e.g. [this LWC fork](https://github.com/Minebench/LWC/tree/pr/worldguard-update)

Stack trace:
```

[19:43:17] [Server thread/INFO]: Phoenix616 issued server command: /cprivate
[19:43:18] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.7.0
[19:43:18] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358)
[19:43:18] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:345)
[19:43:18] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source)
[19:43:18] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67)
[19:43:18] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[19:43:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:43:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[19:43:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1362)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[19:43:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:43:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[19:43:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[19:43:18] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:43:18] [Server thread/WARN]: Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.7.0
[19:43:18] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358)
[19:43:18] [Server thread/WARN]: 	at com.griefcraft.modules.create.CreateModule.onBlockInteract(CreateModule.java:115)
[19:43:18] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:334)
[19:43:18] [Server thread/WARN]: 	... 20 more
[19:43:18] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockVector(Lorg/bukkit/Location;)Lcom/sk89q/worldedit/math/BlockVector3;
[19:43:18] [Server thread/WARN]: 	at com.griefcraft.modules.pluginsupport.WorldGuard.onRegisterProtection(WorldGuard.java:343)
[19:43:18] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:346)
[19:43:18] [Server thread/WARN]: 	... 22 more
```

**Checklist**:

- [ ] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Fawe is in the process of being updated, don't worry, it will be equal with upstream soon again.

**Comment by Phoenix616** [comment]
Good to her that! Why close this issue though if there still is no fixed version available? If it's closed the chance of others having the same issue massively decreases...

**Comment by N0tMyFaultOG** [comment]
> Good to her that! Why close this issue though if there still is no fixed version available? If it's closed the chance of others having the same issue noticing it massively decreases...

Because people tend to search thru issues before opening a new one, also the majority is [on our discord](https://discord.gg/ebreupz) to receive updated about progress and its current status.

**Comment by Sauilitired** [comment]
It makes sense for this to remain open, as the changes have not been merged with the master branch yet. Closing this will only lead to further confusion. This should be closed once the changes are available to everyone :cow:

**Comment by MattBDev** [comment]
- [ ] Vectors
- [ ] BiomeType
- [ ]  BlockType

**Comment by Artuto** [comment]
Update on this? A plugin im using is now broken because the Vector class is missing

**Comment by IronApollo** [comment]
This issue is no longer valid. FAWE has been updated to match somewhere in the Beta 3 API of WorldEdit, maybe higher?

BlockVector_ and Vector_ classes are now the supported classes regarding vectors. The Vector class no longer exists and any plugin attempting to grab that class is simply using outdated API.

Issue closed.

**Comment by DerPavlov** [comment]
I still have the issue that the BlockVector3 in the latest version of FAWE for maven does not exist.
