### ISSUE TITLE
No longer supported schematic format help text needs to be updated from the schematic help command.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#80]
Typing ``/schematic save`` outputs ``Usage: /schematic save [format] <filename>``. Trying to save in that format outputs an error.

The help menu text should instead be updated to reflect the supported schematic save format of ``/schematic save <filename>``.

FAWE tested as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e (03/25 compile).

```
[19:30:56] [Server thread/INFO]: mibby issued server command: //schematic save schematic t
[19:30:56] [Craft Scheduler Thread - 43/INFO]: WorldEdit: mibby (in "creative"): save schematic t
[19:30:56] [Craft Scheduler Thread - 43/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.UnsupportedOperationException: No longer supported.
	at com.sk89q.worldedit.extent.clipboard.io.BuiltInClipboardFormat$1.getWriter(BuiltInClipboardFormat.java:71) ~[?:?]
	at com.sk89q.worldedit.command.SchematicCommands.save(SchematicCommands.java:347) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:331) ~[?:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-584]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-584]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-584]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by N0tMyFaultOG** [comment]
MCEdit doesn’t support 1.13 so schematic's have been changed to `.schem`

**Comment by mibby** [comment]
Noted. The help language will need to be changed then. :)
