### ISSUE TITLE
NoSuchMethodError - worldedit.util.Location.toVector()Lcom/sk89q/worldedit/math/Vector3

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#87]
Compiled FAWE 1.13 as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commits/new-vector-system

Tested with WorldGuard dev 1834 & WorldGuard dev 1830.

Broke in this commit with removal of toVector?
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/92a7bd5e44dbf34870e90d66f224b66ef1e09508

```
[00:38:06] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to WorldGuard v7.0.0-SNAPSHOT;1830-e2ffab5
java.lang.NoSuchMethodError: com.sk89q.worldedit.util.Location.toVector()Lcom/sk89q/worldedit/math/Vector3;
	at com.sk89q.worldguard.protection.regions.QueryCache.queryContains(QueryCache.java:58) ~[?:?]
	at com.sk89q.worldguard.protection.regions.RegionQuery.getApplicableRegions(RegionQuery.java:97) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:649) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor240.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-597]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:479) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:399) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.World.addEntity(World.java:1094) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:942) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.addEntity(CraftWorld.java:1439) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.spawn(CraftWorld.java:1446) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.spawn(CraftWorld.java:1050) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.spawnEntity(CraftWorld.java:395) ~[patched_1.13.2.jar:git-Paper-597]
	at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:132) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.AbstractShopkeeper.spawn(AbstractShopkeeper.java:482) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.activateShopkeeper(SKShopkeeperRegistry.java:361) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.loadShopkeepersInChunk(SKShopkeeperRegistry.java:452) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.loadShopkeepersInChunk(SKShopkeeperRegistry.java:425) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.WorldListener.lambda$onChunkLoad$0(WorldListener.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1009) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-597]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by boy0001** [comment]
thanks, fixed.

**Comment by mibby** [comment]
Thanks @boy0001, glad to see you back!

Confirmed fixed with WorldGuard dev 1830. 

WorldGuard dev 1834 errors but that's because it relies on recent upstream WorldEdit changes made yesterday.

```
[01:10:08] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to WorldGuard v7.0.0-SNAPSHOT;1834-c7ed493
java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(Lorg/bukkit/entity/Player;)V
	at com.sk89q.worldguard.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:43) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:39) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.wrapPlayer(WorldGuardPlugin.java:349) ~[?:?]
	at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.onPlayerJoin(BukkitSessionManager.java:62) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor217.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-597]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:169) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:65) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:271) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1131) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-597]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:10:17] [Server thread/WARN]: [WorldGuard] Task #91 for WorldGuard v7.0.0-SNAPSHOT;1834-c7ed493 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(Lorg/bukkit/entity/Player;)V
	at com.sk89q.worldguard.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:43) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:39) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.wrapPlayer(WorldGuardPlugin.java:349) ~[?:?]
	at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.run(BukkitSessionManager.java:69) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1009) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-597]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
